### ISSUE TITLE
yarn install fails

### ISSUE THREAD

**Issue by ThomasRoest** [FrontendMasters/api-design-node-v3#2]
yarn install fails with 

`error https://registry.yarnpkg.com/flatmap-stream/-/flatmap-stream-0.1.2.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Unexpected end of data"`

no problems with npm though

also see https://github.com/FrontendMasters/api-design-node-v3/pull/1

**Comment by ThomasRoest** [comment]
https://github.com/FrontendMasters/api-design-node-v3/pull/1

**Comment by 1Marc** [comment]
Fixed, thanks!
