### ISSUE TITLE
what's v3 really means?

### ISSUE THREAD

**Issue by xgqfrms** [FrontendMasters/api-design-node-v3#23]
# what's v3 really means? ([Course] API design in Node with Express v3)

> in `package.json` file, I found express is using version 4.x, that's very confused me!

Maybe, it means the tutorials version 3?

https://github.com/FrontendMasters/api-design-node-v3/blob/master/package.json

```js
// "express": "^4.16.4",

```

**Comment by chucksteinmn** [comment]
It's version 3 of the frontendmaster.com course

**Comment by xgqfrms** [comment]
@chucksteinmn thx, I got that. 😀
