### ISSUE TITLE
Dependencies not installing

### ISSUE THREAD

**Issue by usmanrehmat556** [FrontendMasters/api-design-node-v3#34]
I just clone this repo and tried to install all the dependencies as mentioned in the package.json file but it did not work for me!

**Comment by usmanrehmat556** [comment]
error showing me is as follows
bcrypt@3.0.3 install: `node-pre-gyp install --fallback-to-build`
can you fix it or tell me ?

**Comment by chuckcharles** [comment]
I had to replace bcrypt with bcryptjs in package.json and then update user.model.js to use bcryptjs.
I also had to:
npm install --save-dev mock-req-res
npm install --save-dev sinon
Then run npm install

**Comment by usmanrehmat556** [comment]
Thank you @chuckcharles.
