### ISSUE TITLE
jest giving error   Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout. on some tests

### ISSUE THREAD

**Issue by alvinlal** [FrontendMasters/api-design-node-v3#40]

**Comment by brunogonzales** [comment]
@alvinlal did you find out what was causing this? I'm getting this same error

**Comment by alvinlal** [comment]
@brunogonzales the problem was because of the default timeout value of jest which is 5000ms.That is any test that takes more than 5000ms will be failed.You can change the default value to a higher value to solve this problem.But i am not sure how to do that as  i have no experience with jest.

**Comment by brunogonzales** [comment]
So you never ended up passing the tests?

**Comment by alvinlal** [comment]
@brunogonzales some test passed and some didn't.I tried to create a jest configuration file and set the default timeout value but that didnt work,let me know if you find any fix,

**Comment by brunogonzales** [comment]
@alvinlal I found the solution. You can add ` jest.setTimeout(10000)` anywhere to `test-db-setup.js` to increase the Jest's default timeout. 
![image](https://user-images.githubusercontent.com/57231813/80394581-a80afe80-8877-11ea-9a5f-6ed302194031.png)

**Comment by alvinlal** [comment]
@brunogonzales Thanks so much!
