### ISSUE TITLE
Cannot find module bcrypt_lib.node from 'bcrypt.js

### ISSUE THREAD

**Issue by Tyrone-Cartwright** [FrontendMasters/api-design-node-v3#41]
$ npm run test-routes

> api-design-v3@1.0.0 test-routes C:\Users\tyrone\Desktop\FEM-API\api-design-node-v3
> npm run test -t router

> api-design-v3@1.0.0 test C:\Users\tyrone\Desktop\FEM-API\api-design-node-v3> NODE_ENV=testing jest --forceExit --detectOpenHandles  --silent "router"   

 FAIL  src/resources/item/__tests__/item.router.spec.js
  ● Test suite failed to run

    Cannot find module 'C:\Users\tyrone\Desktop\FEM-API\api-design-node-v3\node_modules\bcrypt\lib\binding\bcrypt_lib.node' from 'bcrypt.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:221:17)
      at Object.<anonymous> (node_modules/bcrypt/bcrypt.js:6:16)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.972s
Note: This command was run via npm module 'win-node-env'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! api-design-v3@1.0.0 test: `NODE_ENV=testing jest --forceExit --detectOpenHandles  --silent "router"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the api-design-v3@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above. 

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tyrone\AppData\Roaming\npm-cache\_logs\2020-01-23T14_35_37_508Z-debug.log    
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! api-design-v3@1.0.0 test-routes: `npm run test -t router`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the api-design-v3@1.0.0 test-routes script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above. 

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tyrone\AppData\Roaming\npm-cache\_logs\2020-01-23T14_35_37_672Z-debug.log

**Comment by smapets** [comment]
I had the same issue... Any progress??

**Comment by reviakin** [comment]
@smapets 
@Tyrone-Cartwright 
try
- remove your node_modules folder
- check node's version ( 'node -v' )
- if it isn't 9, change version ('nvm use 9'). 
- after setup node's version install packages ( 'yarn' or 'npm i'  )
